import { useState } from "react";
import { Search, Plus, LayoutGrid, List, SlidersHorizontal } from "lucide-react";
import { useLeads } from "../context/LeadsContext";
import { stageColors } from "../data/dummyLeads";
import AddLeadModal from "../components/AddLeadModal";
import { useAuth } from "../context/AuthContext";
import { useNavigate } from "react-router-dom";

export default function Leads(){const {leads}=useLeads();const {user}=useAuth();const isAdmin=user?.role==="admin";const navigate=useNavigate();const [q,setQ]=useState("");const [show,setShow]=useState(false);const filtered=leads.filter(l=>`${l.name} ${l.company||""} ${l.email||""}`.toLowerCase().includes(q.toLowerCase()));return <div className="workspace-page">
<header className="page-header"><div><div className="breadcrumb">Workspace / All cards</div><h1>All Cards</h1><p>Search and inspect every CRM record from one project view.</p></div>{isAdmin && <button className="primary-button" onClick={()=>setShow(true)}><Plus size={17}/> Add card</button>}</header>
<div className="content-toolbar"><label className="search-box wide"><Search size={16}/><input placeholder="Search cards, companies or email…" value={q} onChange={e=>setQ(e.target.value)}/></label><button className="secondary-button"><SlidersHorizontal size={15}/> Filters</button><div className="view-toggle"><button className="active"><List size={16}/></button><button onClick={()=>navigate('/boards')}><LayoutGrid size={16}/></button></div></div>
<div className="table-card"><table><thead><tr><th>Card</th><th>Company</th><th>Stage</th><th>Source</th><th>Owner</th></tr></thead><tbody>{filtered.map(l=>{const c=stageColors[l.stage]||stageColors.New;return <tr key={l.id} onClick={()=>navigate(`/leads/${l.id}`)}><td><strong>{l.name}</strong><small>{l.email||l.phone||"No contact details"}</small></td><td>{l.company||"—"}</td><td><span className="status-chip" style={{background:c.bg,color:c.text}}>{l.stage}</span></td><td>{l.source||"—"}</td><td><span className="avatar">{l.assignedTo?.[0]||"?"}</span>{l.assignedTo}</td></tr>})}</tbody></table>{filtered.length===0&&<div className="empty-state">No cards match your search.</div>}</div>{show&&isAdmin&&<AddLeadModal onClose={()=>setShow(false)}/>}</div>}